<?php

namespace Phabalicious\Command;

use Phabalicious\Configuration\ConfigurationService;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class AboutCommand extends BaseCommand
{
    protected static $defaultName = 'about';

    public function __construct(ConfigurationService $configuration, $name = null) {
        parent::__construct($configuration, $name);
    }

    protected function configure()
    {
        parent::configure();
        $this
            ->setName('about')
            ->setDescription('shows the configuration')
            ->setHelp('Shows a detailed view of all configuration of that specific host');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
        $output->writeln('about');
    }

}