<?php

/** @noinspection PhpRedundantCatchClauseInspection */

namespace Phabalicious\Command;

use Phabalicious\Configuration\HostConfig;
use Phabalicious\Exception\EarlyTaskExitException;
use Phabalicious\Exception\MethodNotFoundException;
use Phabalicious\Method\DockerMethod;
use Phabalicious\ShellCompletion\FishShellCompletionContext;
use Phabalicious\Utilities\Utilities;
use Stecman\Component\Symfony\Console\BashCompletion\CompletionContext;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class DockerCommand extends BaseCommand
{
    protected function configure(): void
    {
        parent::configure();
        $this
            ->setName('docker')
            ->setDescription('Run one or more specific docker tasks')
            ->addArgument(
                'docker',
                InputArgument::IS_ARRAY | InputArgument::REQUIRED,
                'docker tasks to run'
            )
            ->setHelp('
Runs one or more docker tasks defined in the docker configuration.

Docker tasks are custom operations defined in your docker configuration section.
They can include starting/stopping containers, running docker-compose commands,
or executing custom scripts in the docker environment.

Behavior:
- Requires host configuration with docker integration enabled
- Looks up tasks from the docker configuration\'s "tasks" section
- Includes internal docker tasks provided by the docker method
- Runs tasks sequentially if multiple tasks are specified
- Shows available tasks if specified task doesn\'t exist

Tasks can be defined in your fabfile under dockerHosts:

<info>dockerHosts:
  my-docker:
    tasks:
      custom-build:
        - docker build -t myapp .</info>

Arguments:
- <docker>: One or more docker task names to run

Examples:
<info>phab --config=myconfig docker up</info>
<info>phab --config=myconfig docker down build up</info>  # Run multiple tasks
<info>phab --config=myconfig docker custom-task</info>
            ');
    }

    public function completeArgumentValues($argumentName, CompletionContext $context): array
    {
        if (('docker' == $argumentName) && ($context instanceof FishShellCompletionContext)) {
            $host_config = $context->getHostConfig();
            if ($host_config) {
                $docker_config = $context->getDockerConfig($host_config->getConfigName());

                return $docker_config ? array_keys($this->getAllTasks($docker_config)) : [];
            }
        }

        return parent::completeArgumentValues($argumentName, $context); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Phabalicious\Exception\BlueprintTemplateNotFoundException
     * @throws \Phabalicious\Exception\FabfileNotFoundException
     * @throws \Phabalicious\Exception\FabfileNotReadableException
     * @throws MethodNotFoundException
     * @throws \Phabalicious\Exception\MismatchedVersionException
     * @throws \Phabalicious\Exception\MissingDockerHostConfigException
     * @throws \Phabalicious\Exception\ShellProviderNotFoundException
     * @throws \Phabalicious\Exception\TaskNotFoundInMethodException
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        if ($result = parent::execute($input, $output)) {
            return $result;
        }

        $context = $this->getContext();
        $docker_config = $this->getDockerConfig();
        $context->set('docker_config', $docker_config);

        if (!$docker_config) {
            $docker_config_name = $this->getHostConfig()->getData()->getProperty('docker.configuration', false);
            $msg = $docker_config_name
                ? sprintf(
                    'Host-configuration `%s` has no docker configuration named `%s`!',
                    $this->getHostConfig()->getConfigName(),
                    $docker_config_name
                )
                : sprintf(
                    'Host-configuration `%s` has no docker-configuration!',
                    $this->getHostConfig()->getConfigName()
                );
            throw new \RuntimeException($msg);
        }

        $tasks = $input->getArgument('docker');
        if (!is_array($tasks)) {
            $tasks = [$tasks];
        }
        try {
            $all_tasks = $this->getAllTasks($docker_config);
            foreach ($tasks as $task) {
                if (empty($all_tasks[$task])) {
                    $this->printAvailableTasks($input, $output, $all_tasks);
                    throw new MethodNotFoundException('Missing task `'.$task.'`');
                }
                $context->set('docker_task', $task);

                $this->getMethods()
                    ->runTask('docker', $this->getHostConfig(), $context);
            }

            return $context->getResult('exitCode', 0);
        } catch (EarlyTaskExitException $e) {
            return 1;
        }
    }

    /**
     * @return array|mixed
     *
     * @throws MethodNotFoundException
     */
    private function getAllTasks(HostConfig $docker_config): mixed
    {
        $tasks = $docker_config->get('tasks', []);
        /** @var DockerMethod $method */
        $method = $this->getConfiguration()->getMethodFactory()->getMethod('docker');

        return Utilities::mergeData($tasks, array_combine(
            $method->getInternalTasks(),
            $method->getInternalTasks()
        ));
    }

    private function printAvailableTasks(InputInterface $input, OutputInterface $output, $tasks)
    {
        $io = new SymfonyStyle($input, $output);
        $io->title('List of docker tasks:');
        $io->listing(array_keys($tasks));
    }
}
