questions:
  platform:
    question: "What platform are you working on (mac-intel|mac-arm|linux)"
    type: choices
    default: mac-intel
    choices:
      - mac-intel
      - mac-arm
      - linux
  branch:
    question: "What branch should I use to checkout?"
    default: main
  runSetup:
    question: "Run the host- and docker setup?"
    default: true
    type: confirm

variables:
  name: MultiBaseBox

