questions:
  platform:
    question: "What platform are you working on (mac|linux)"
    type: choices
    default: mac
    choices:
      - mac
      - linux
  branch:
    question: "What branch should I use to checkout?"
    default: master
  runSetup:
    question: "Run the host- and docker setup?"
    default: true
    type: confirm

variables:
  name: MultiBaseBox

