# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: factorial/phabalicious-test-runner

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: php /composer.phar install

      - save_cache:
          paths:
            - ./vendor
          key: v2-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: cd tests; ../vendor/bin/phpunit --exclude-group docker .
