site_name: Phabalicious
theme: readthedocs
markdown_extensions:
  - admonition

repo_url: https://github.com/factorial-io/phabalicious/
repo_name: GitHub
edit_uri: edit/develop/docs/docs/
site_description: Phabalicious Documentation
site_author: Factorial GmbH, Hamburg
copyright: © 2018 Factorial GmbH, Hamburg

pages:
  - index.md
  - installation.md
  - usage.md
  - available-tasks.md
  - configuration.md
  - docker-integration.md
  - local-overrides.md
  - app-scaffold.md
  - contribute.md
  - Changelog.md
extra_css:
  - css/version-select.css
extra_javascript:
  - js/version-select.js
