# based on parts of PPCRE.
#
# (c) Serghei Iakovlev <egrep@protonmail.ch>
# (c) Stephan Huber <stephan@factorial.io>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: Create phar and release

on:
    push:
        tags:
            - "*"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  extensions: intl, zip, zlib
                  coverage: none
                  ini-values: memory_limit=1G, phar.readonly=0

            - name: Install Project Dependencies
              run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

            - name: Install Box
              run: |
                  wget \
                    "https://github.com/humbug/box/releases/download/4.6.2/box.phar" \
                    --quiet \
                    -O ./box
                  chmod +x ./box
                  sudo mv ./box /usr/local/bin
            - name: Build Application PHAR
              run: git describe && composer build-phar

            - name: Getting Tag Name
              id: get-version
              run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

            - name: Self-Test
              run: ./build/phabalicious.phar --version

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  # This token is provided by GitHub Actions.
                  # You DO NOT need to create your own token.
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: ${{ steps.get-version.outputs.version }}
                  tag: ${{ steps.get-version.outputs.version }}
                  body: "Next stable release."
                  # This will update existing tags if any
                  allowUpdates: true
                  artifacts: ./build/phabalicious.phar
                  artifactContentType: application/x-php

    homebrew:
        name: Update Homebrew formula
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repo (phabalicious)
              uses: actions/checkout@v5

            - name: Checkout tap repo
              uses: actions/checkout@v5
              with:
                  repository: factorial-io/homebrew-phabalicious
                  token: ${{ secrets.ACCESS_TOKEN }}
                  path: tap

            - name: Extract version and determine formula
              id: version
              run: |
                  VERSION=${GITHUB_REF#refs/tags/}
                  echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

                  # Determine which formula to update based on version
                  if [[ $VERSION =~ ^4\. ]]; then
                    # Version 4.x -> phab@4.rb
                    echo "formula=phab@4.rb" >> "$GITHUB_OUTPUT"
                    echo "template=phabalicious-v4.rb.tpl" >> "$GITHUB_OUTPUT"
                  elif [[ $VERSION =~ ^3\.8 ]]; then
                    # Version 3.8.x -> phab.rb only
                    echo "formula=phab.rb" >> "$GITHUB_OUTPUT"
                    echo "template=phabalicious.rb.tpl" >> "$GITHUB_OUTPUT"
                  else
                    # Unsupported version - fail
                    echo "Unsupported version: ${VERSION}"
                    echo "Only 3.8.x and 4.x versions are supported"
                    exit 1
                  fi

            - name: Download and compute SHA
              id: sha
              run: |
                  VERSION=${{ steps.version.outputs.version }}
                  BASE_URL="https://github.com/factorial-io/phabalicious/releases/download/${VERSION}"

                  curl -LO "${BASE_URL}/phabalicious.phar"

                  echo "sha=$(shasum -a 256 phabalicious.phar | awk '{print $1}')" >> "$GITHUB_OUTPUT"

            - name: Copy and render formula template
              run: |
                  FORMULA_FILE="${{ steps.version.outputs.formula }}"
                  TEMPLATE="${{ steps.version.outputs.template }}"
                  FORMULA_PATH="Formula/${FORMULA_FILE}"

                  cp packaging/$TEMPLATE tap/$FORMULA_PATH

                  sed -i "s|VERSION_PLACEHOLDER|${{ steps.version.outputs.version }}|" tap/$FORMULA_PATH
                  sed -i "s|URL_PLACEHOLDER|https://github.com/factorial-io/phabalicious/releases/download/${{ steps.version.outputs.version }}/phabalicious.phar|" tap/$FORMULA_PATH
                  sed -i "s|SHA_PLACEHOLDER|${{ steps.sha.outputs.sha }}|" tap/$FORMULA_PATH

            - name: Commit and push formula to tap
              run: |
                  FORMULA_FILE="${{ steps.version.outputs.formula }}"
                  cd tap
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git add "Formula/${FORMULA_FILE}"
                  git commit -m "Update phabalicious formula to ${{ steps.version.outputs.version }}"
                  git push
