# based on parts of PPCRE.
#
# (c) Serghei Iakovlev <egrep@protonmail.ch>
# (c) Stephan Huber <stephan@factorial.io>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: Create phar and release

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=1G, phar.readonly=0

      - name: Install Project Dependencies
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

      - name: Install Box
        run: |
          wget \
            "https://github.com/humbug/box/releases/download/3.11.1/box.phar" \
            --quiet \
            -O ./box
          chmod +x ./box
          sudo mv ./box /usr/local/bin
      - name: Build Application PHAR
        run: git describe && composer build-phar

      - name: Geting Tag Name
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Self-Test
        run: ./build/phabalicious.phar --version

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          # This token is provided by GitHub Actions.
          # You DO NOT need to create your own token.
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.get-version.outputs.version }}
          tag: ${{ steps.get-version.outputs.version }}
          body: 'Next stable release.'
          # This will update existing tags if any
          allowUpdates: true
          artifacts: ./build/phabalicious.phar
          artifactContentType: application/x-php
